In [1]:
# numpy
import numpy as np
# why use numpy - memory efficiency, optimized for mathematical ops, tons of built in functionality

list_a = [5, 6, 7, 8, 9, 10]
# transform this to an np array
np.array(list_a)

array([ 5,  6,  7,  8,  9, 10])

In [2]:
type(list_a)

list

In [3]:
arr = np.array(list_a)
type(arr)

numpy.ndarray

In [4]:
# function arange()
# shift-tab in brackets for func prototype
array_1 = np.arange(0, 10)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array_1 = np.arange(0, 10, 3)
array_1

array([0, 3, 6, 9])

In [6]:
# creating matrices of 0,1
size = (7,3)
matrix = np.ones(size)
matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
matrix = np.zeros((10,10))
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
# random matrix
# (low, high, dims)
rnd = np.random.randint(0, 50, (7,3))
rnd

array([[ 1, 36, 24],
       [28, 37, 12],
       [19, 43, 32],
       [20, 15, 12],
       [26, 42,  3],
       [10, 42, 13],
       [48, 27, 22]])

In [9]:
# create linearly spaced array
# ax+b defines linear, need same space between the values
# good for testing, constant slope
# provide (a, b, numvals)
# Return evenly spaced numbers over a specified interval.
lin = np.linspace(0, 12, num=100)
lin

array([ 0.        ,  0.12121212,  0.24242424,  0.36363636,  0.48484848,
        0.60606061,  0.72727273,  0.84848485,  0.96969697,  1.09090909,
        1.21212121,  1.33333333,  1.45454545,  1.57575758,  1.6969697 ,
        1.81818182,  1.93939394,  2.06060606,  2.18181818,  2.3030303 ,
        2.42424242,  2.54545455,  2.66666667,  2.78787879,  2.90909091,
        3.03030303,  3.15151515,  3.27272727,  3.39393939,  3.51515152,
        3.63636364,  3.75757576,  3.87878788,  4.        ,  4.12121212,
        4.24242424,  4.36363636,  4.48484848,  4.60606061,  4.72727273,
        4.84848485,  4.96969697,  5.09090909,  5.21212121,  5.33333333,
        5.45454545,  5.57575758,  5.6969697 ,  5.81818182,  5.93939394,
        6.06060606,  6.18181818,  6.3030303 ,  6.42424242,  6.54545455,
        6.66666667,  6.78787879,  6.90909091,  7.03030303,  7.15151515,
        7.27272727,  7.39393939,  7.51515152,  7.63636364,  7.75757576,
        7.87878788,  8.        ,  8.12121212,  8.24242424,  8.36

In [10]:
# simple ops
arr = np.random.randint(0, 1000, 80)
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.std())
print(arr.var())
print(arr.std()**2)

999
2
513.325
274.00696957376834
75079.819375
75079.819375


the variance is equal to the square of standard deviation

In [14]:
# 2d and 3d arrays, Nd arrays
arr = np.random.randint(0, 1000, 24)
print(arr) # 1 row, 24 columns
mat = arr.reshape(6,4) #transform into different dimensions, retain values, values must multiply to current shape
print('\n',mat)
mat = arr.reshape(3,2,4)
print('\n', mat)

[579 770 342  91  90 874 202 624 201  20 173 757 412 977 283 310 284 325
 317 696 844 284 801 620]

 [[579 770 342  91]
 [ 90 874 202 624]
 [201  20 173 757]
 [412 977 283 310]
 [284 325 317 696]
 [844 284 801 620]]

 [[[579 770 342  91]
  [ 90 874 202 624]]

 [[201  20 173 757]
  [412 977 283 310]]

 [[284 325 317 696]
  [844 284 801 620]]]


In [12]:
# Filtering and locating values in array
print(mat[0, 1])
mat>100 #return array of booleans of which elements are greater than 100
mat = mat[mat>500] #cull all values less than 100, make new array with one row
print(mat)

818
[659 818 736 837 522 932 535 973 750 892 643 522 916 972 527 503 981 949
 945]


In [13]:
# Seed function
np.random.seed(707) # the "random" output will always remain the same. Seed sets up the psuedorandom generator
# good for having consistent testing arrays. PRNG has a starting state that determines all following states
random_matrix = np.random.randint(0,100,10)
random_matrix

array([91, 31, 99, 44, 39, 77, 58, 45, 10, 74])